import { useEffect, useState } from 'react'
import { CloudArrowUpIcon, ExclamationTriangleIcon, WifiIcon } from '@heroicons/react/24/outline'
import { listOfflineChanges, queueOfflineChange, resolveConflict, syncOfflineChanges, type OfflineOperation, type SyncResult } from '../services/offlineSyncService'

export default function OfflineSyncPage() {
  const [queue, setQueue] = useState<OfflineOperation[]>([])
  const [online, setOnline] = useState(navigator.onLine)
  const [syncing, setSyncing] = useState(false)
  const [results, setResults] = useState<SyncResult[]>([])
  const [message, setMessage] = useState<string | null>(null)
  const refresh = () => void listOfflineChanges().then(setQueue)
  useEffect(() => { refresh(); const status = () => { setOnline(navigator.onLine); if (navigator.onLine) void synchronize() }; window.addEventListener('online', status); window.addEventListener('offline', status); const timer = window.setInterval(() => { if (navigator.onLine) void synchronize() }, 15_000); return () => { window.removeEventListener('online', status); window.removeEventListener('offline', status); window.clearInterval(timer) } }, [])
  const synchronize = async () => { if (syncing || !navigator.onLine) return; setSyncing(true); try { const next = await syncOfflineChanges(); setResults(next); setMessage(next.some(item => item.status === 'conflict') ? 'A conflict needs an explicit choice.' : next.length ? 'Queued work synchronized.' : null); refresh() } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Synchronization will retry automatically.'); refresh() } finally { setSyncing(false) } }
  const stagePreference = async () => { await queueOfflineChange('preference', 'offline-sync-demo', { updatedAt: new Date().toISOString() }); refresh(); setMessage('Preference update stored in IndexedDB.') }
  return <main className="mx-auto max-w-4xl space-y-5"><section className="rounded-[2rem] border border-slate-200 bg-gradient-to-br from-white via-cyan-50 to-violet-50 p-6 shadow-sm sm:p-10 dark:border-slate-800 dark:from-slate-900 dark:via-cyan-950/30 dark:to-slate-950"><div className="flex justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-cyan-700">Offline workspace</p><h1 className="mt-2 text-3xl font-semibold sm:text-5xl">Your work waits safely.</h1><p className="mt-3 max-w-2xl text-slate-600 dark:text-slate-300">Versioned local records synchronize across reconnects and browser tabs.</p></div><span className="inline-flex h-fit items-center gap-2 rounded-full bg-emerald-100 px-3 py-2 text-sm font-semibold text-emerald-800"><WifiIcon className="h-4 w-4" />{online ? 'Online' : 'Offline'}</span></div></section>{message ? <p role="status" className="rounded-2xl border border-slate-200 bg-white p-4 text-sm dark:bg-slate-900">{message}</p> : null}<section className="grid gap-5 md:grid-cols-2"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-[.2em] text-violet-600">Local queue</p><p className="mt-3 text-4xl font-semibold">{queue.length}</p><button type="button" onClick={() => void stagePreference()} className="mt-5 min-h-11 w-full rounded-full border border-slate-300 px-4 text-sm font-semibold">Queue a local update</button></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-600">Sync control</p><button type="button" disabled={!online || !queue.length || syncing} onClick={() => void synchronize()} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-full bg-violet-600 px-4 text-sm font-semibold text-white disabled:opacity-50"><CloudArrowUpIcon className="h-4 w-4" />{syncing ? 'Synchronizing…' : 'Synchronize now'}</button></div></section>{results.length ? <section className="rounded-[1.5rem] border border-slate-200 bg-white p-5 dark:bg-slate-900"><h2 className="text-xl font-semibold">Latest result</h2>{results.map(result => <div key={result.operationId} className="mt-3 flex items-center justify-between rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-950"><code>{result.operationId}</code>{result.status === 'conflict' ? <span><ExclamationTriangleIcon className="mr-1 inline h-4 w-4" />Conflict <button className="ml-2 underline" onClick={() => void resolveConflict(result.operationId, 'local').then(synchronize)}>Keep local</button><button className="ml-2 underline" onClick={() => void resolveConflict(result.operationId, 'remote').then(refresh)}>Use remote</button></span> : <strong>{result.status}</strong>}</div>)}</section> : null}</main>
}

