name: Project Sync

on:
  issues:
    types:
      - opened
      - reopened
      - edited
      - closed
      - labeled
      - unlabeled
      - assigned
      - unassigned

  pull_request:
    types:
      - opened
      - reopened
      - edited
      - closed
      - labeled
      - unlabeled
      - assigned
      - unassigned
      - review_requested
      - ready_for_review
      - converted_to_draft

  workflow_dispatch:

jobs:
  sync:
    if: ${{ github.event_name != 'issues' || github.event.issue.pull_request == null }}
    uses: michelecoppi/sit_infrastructure/.github/workflows/reusable-project-sync.yml@main
    with:
      project-url: ${{ vars.PROJECT_URL }}
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}